stages:
  - build

variables:
  msbuild: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'

build_patcher:
    stage: build
    tags:
        - windows
    only:
        changes:
            - Patcher/**/*
    script:
        - '& $msbuild .\Patcher\Hitman2Patcher.sln /t:Build /p:Configuration=Release'
        - 'mv .\Patcher\bin\x64\Release\Hitman2Patcher.exe .\Hitman2Patcher.exe'
    artifacts:
        name: "LocalGhost-PatcherBinary-$env:CI_COMMIT_SHORT_SHA"
        when: on_success
        expire_in: never
        paths:
            - Hitman2Patcher.exe